### ISSUE TITLE
How to ues this code

### ISSUE THREAD

**Issue by TheLiao233** [gq-max/AdvDiffVLM#1]
Hello, I would like to ask what steps should be followed to use this code to generate adversarial samples?

In addition, could you please provide your environment dependencies?

Thanks

**Comment by gq-max** [comment]
Thank you for your attention to our work. The running code is being sorted out.

**Comment by TheLiao233** [comment]
> Thank you for your attention to our work. The running code is being sorted out.

Thank you very much for your reply. 

May I ask how long it will take? If it takes a long time, I may have to consider manually implementing some content to test whether it is effective for my current work.
